# Generated by Django 2.2 on 2019-04-18 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='收件人')),
                ('telphone', models.CharField(max_length=255, verbose_name='联系电话')),
                ('province', models.CharField(max_length=255, verbose_name='省')),
                ('city', models.CharField(max_length=255, verbose_name='市')),
                ('detail', models.CharField(max_length=255, verbose_name='地址详情')),
                ('note', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单地址',
                'verbose_name_plural': '订单地址',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单日期')),
                ('day', models.DateField(auto_now_add=True, verbose_name='创建日')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderAdress', verbose_name='地址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
            },
        ),
        migrations.CreateModel(
            name='LogisticType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='物流名称')),
                ('website', models.CharField(max_length=255, verbose_name='物流网站')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '物流类型',
                'verbose_name_plural': '物流类型',
            },
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发货时间')),
                ('num', models.CharField(max_length=255, verbose_name='单号')),
                ('logistic_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.LogisticType', verbose_name='物流公司')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '物流列表',
                'verbose_name_plural': '物流列表',
            },
        ),
    ]
