# Generated by Django 2.2 on 2019-04-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderadress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=255, null=True, verbose_name='家居类型'),
        ),
    ]
