# Generated by Django 2.2 on 2019-04-15 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='家电名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 1, 6, 639793), verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '家居类型',
                'verbose_name_plural': '家居类型',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='类别名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 1, 6, 640515), verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('params', models.TextField(verbose_name='参数')),
                ('furnituretype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.FurnitureType')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='设备名称')),
                ('num', models.IntegerField(default=0, verbose_name='设备数量')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType')),
            ],
            options={
                'verbose_name': '设备明细',
                'verbose_name_plural': '设备明细',
            },
        ),
    ]
