# Generated by Django 2.2 on 2019-04-15 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备列表', 'verbose_name_plural': '设备列表'},
        ),
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 22, 43, 161707), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='devices.DeviceType'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 22, 43, 160927), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='furnituretype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type', to='devices.FurnitureType'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 22, 43, 160246), verbose_name='创建时间'),
        ),
    ]
