# Generated by Django 2.2 on 2019-04-16 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190415_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 0, 49, 11, 879496), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 0, 49, 11, 878249), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='furnituretype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type', to='devices.FurnitureType', verbose_name='所属家居'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 0, 49, 11, 877513), verbose_name='创建时间'),
        ),
    ]
