# Generated by Django 2.2 on 2019-04-21 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20190418_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 6, 57, 57, 259544), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 6, 57, 57, 258482), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='deviceuse',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 6, 57, 57, 260559), verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 6, 57, 57, 257135), verbose_name='创建时间'),
        ),
    ]
