# Generated by Django 2.2 on 2019-04-23 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20190423_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 7, 56, 57, 229652), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 7, 56, 57, 228406), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='deviceuse',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 7, 56, 57, 230426), verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='deviceuse',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_device', to='orders.Order', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 7, 56, 57, 227278), verbose_name='创建时间'),
        ),
    ]
