# Generated by Django 2.2 on 2019-04-27 02:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20190427_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 2, 42, 36, 325655), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 2, 42, 36, 324771), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='deviceuse',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 2, 42, 36, 326395), verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 2, 42, 36, 323977), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='devices.FurnitureType', verbose_name='所属家居'),
        ),
    ]
