# Generated by Django 2.2 on 2019-05-14 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20190427_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '答案', 'verbose_name_plural': '答案'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 2, 37, 84935), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 2, 37, 82509), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='deviceuse',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 2, 37, 86290), verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
