# Generated by Django 2.2 on 2019-04-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0006_auto_20190421_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='日志提交时间')),
                ('day', models.DateField(auto_now_add=True, verbose_name='日志时间')),
                ('info', models.TextField(verbose_name='使用详情')),
                ('forniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.FurnitureType', verbose_name='家居类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '设备使用情况',
                'verbose_name_plural': '设备使用情况',
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户提交时间')),
                ('day', models.DateField(auto_now_add=True, verbose_name='日志时间')),
                ('type', models.CharField(max_length=255, verbose_name='操作类型')),
                ('time', models.IntegerField(default=0, verbose_name='时间长度')),
                ('forniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.FurnitureType', verbose_name='家居类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '设备日志',
                'verbose_name_plural': '设备日志',
            },
        ),
    ]
